version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing frontend dependencies...
      - cd library_frontend
      - npm install --unsafe-perm

  build:
    commands:
      - echo Building React frontend...
      - cd library_frontend
      - node node_modules/vite/bin/vite.js build
      - echo React build complete.

artifacts:
  files:
    - library_backend/**/*
    - library_frontend/dist/**/*
    - appspec.yml
    - scripts/**/*
    -  .sh
  discard-paths: no
